"""Renumber source-prefixed citations (sys:N, sep:N, idc:N) to integer
\\bibitem keys in order of first citation, merging duplicate works by
title. Writes chapters/bibliography.tex and sources/bib_key_map.txt, and
rewrites the \\cite keys in the chapter files."""
import re, os
TH = '/Users/christopherwaight/Desktop/Multirobot_Testbed/Paper_Writing/PhD Thesis/'
ORDER = ['ch01_introduction', 'ch02_verification_tools', 'ch03_preliminaries',
         'ch04_estimation_framework', 'ch05_zeroth_order', 'ch06_first_order',
         'ch07_second_order', 'ch08_crosscutting', 'ch09_limitations',
         'ch10_conclusion', 'appA_fields', 'appB_kinematics3', 'appC_kinematics6',
         'appD_frame_equivariance', 'appE_stability', 'appF_statistics']
PREFER = {'sys': 0, 'idc': 1, 'sep': 2}   # full journal names first

entries = {}
for f in ['bib_sources.tex', 'bib_idetc.tex']:
    for line in open(TH + 'chapters/' + f):
        m = re.match(r'\\bibitem\{([a-z]+:\d+)\}\s*(.*)', line.strip())
        if m:
            entries[m.group(1)] = m.group(2)

def title(body):
    m = re.search(r'``(.+?)\'\'|"(.+?)"', body)
    t = (m.group(1) or m.group(2)) if m else body
    return re.sub(r'[^a-z0-9]', '', t.lower())

groups = {}
for k, b in entries.items():
    groups.setdefault(title(b), []).append(k)
# Same work, different titles in the two papers. Draft_11's ref 9 title
# ("downscaling, and applications") appears wrong; use the Systems entry.
ALIAS = {'sep:9': 'sys:40'}
canon = {k: min(g, key=lambda x: (PREFER[x.split(':')[0]], int(x.split(':')[1])))
         for g in groups.values() for k in g}
canon.update(ALIAS)

num, order = {}, []
texts = {}
for name in ORDER:
    t = open(TH + f'chapters/{name}.tex').read()
    texts[name] = t
    for m in re.finditer(r'\\cite\{([^}]*)\}', t):
        for k in m.group(1).split(','):
            k = k.strip()
            if k not in entries:
                raise SystemExit(f'{name}: unknown cite key {k}')
            c = canon[k]
            if c not in num:
                num[c] = len(order) + 1
                order.append(c)

def fix(m):
    ks = []
    for k in m.group(1).split(','):
        n = str(num[canon[k.strip()]])
        if n not in ks:
            ks.append(n)
    return '\\cite{' + ','.join(ks) + '}'

for name, t in texts.items():
    open(TH + f'chapters/{name}.tex', 'w').write(re.sub(r'\\cite\{([^}]*)\}', fix, t))

def quotes(b):
    return re.sub(r'"(.+?)"', r"``\1''", b)

out = ['% Generated by sources/assemble/build_bib.py. Order of first citation.']
for c in order:
    out.append(f'\\bibitem{{{num[c]}}} {quotes(entries[c])}')
open(TH + 'chapters/bibliography.tex', 'w').write('\n\n'.join(out) + '\n')

with open(TH + 'sources/bib_key_map.txt', 'w') as f:
    f.write('# source-prefixed key -> thesis reference number (cited works only)\n')
    for k in sorted(entries, key=lambda x: (x.split(':')[0], int(x.split(':')[1]))):
        if canon[k] in num:
            f.write(f'{k}\t{num[canon[k]]}\n')
print(f'{len(order)} references cited')
