"""
HexstarSnapCluster — generated by clusterbuilder.py
Config: hub-and-spoke, 6 robots
State variables: ['x_h', 'y_h', 'theta_c', 'r_1', 'r_2', 'r_3', 'r_4', 'r_5', 'gamma_2', 'gamma_3', 'gamma_4', 'gamma_5']
"""
import os
import yaml
import numpy as np
from src.robot.omnibot import Omnibot
from hexstar_snap_forward_kinematics import forward_kinematics
from hexstar_snap_inverse_kinematics import inverse_kinematics
from hexstar_snap_inverse_jacobian import inverse_jacobian, STATE_VARS


class HexstarSnapCluster:

    def __init__(self, formation_config_path, field, timestep=0.1, momentum_alpha=0.7):
        
        self.field = field
        self.timestep = timestep
        self.momentum_alpha = momentum_alpha
        self._load_formation_config(formation_config_path)
        self._initialize_robots()
        self.center_history = []
        self.robot_history = []
        self.velocity_history = []

    def _load_formation_config(self, config_path):
        if not os.path.isabs(config_path):
            script_dir = os.path.dirname(os.path.abspath(__file__))
            config_path = os.path.join(script_dir, config_path)
        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
        formation = config['formation']
        self.N = formation['num_robots']
        self.desired_r_1 = formation['r_1']
        self.desired_r_2 = formation['r_2']
        self.desired_r_3 = formation['r_3']
        self.desired_r_4 = formation['r_4']
        self.desired_r_5 = formation['r_5']
        self.desired_gamma_2 = formation['gamma_2']
        self.desired_gamma_3 = formation['gamma_3']
        self.desired_gamma_4 = formation['gamma_4']
        self.desired_gamma_5 = formation['gamma_5']
        self.position_gain = formation.get('position_gain', 1.0)
        self.angle_gain = formation.get('angle_gain', 0.1)

    def _initialize_robots(self):
        import math, random
        default = {'x_h': 0.0, 'y_h': 0.0, 'theta_c': 0.0, 'r_1': 0.3, 'r_2': 0.3, 'r_3': 0.3, 'r_4': 0.3, 'r_5': 0.3, 'gamma_2': 1.2566370614359172, 'gamma_3': 2.5132741228718345, 'gamma_4': -2.5132741228718345, 'gamma_5': -1.2566370614359172}
        default['x_c' if 'x_c' in default else 'x_h'] = random.uniform(-0.5, 0.5)
        default['y_c' if 'y_c' in default else 'y_h'] = random.uniform(-0.5, 0.5)
        positions = inverse_kinematics(default)
        self.robots = [Omnibot(positions[i+1][0], positions[i+1][1],
                               self.timestep, self.momentum_alpha)
                       for i in range(6)]

    def get_robot_positions(self):
        return {i+1: tuple(self.robots[i].get_position()) for i in range(6)}

    def get_current_formation(self):
        pos = self.get_robot_positions()
        coords = []
        for i in range(1, 6+1):
            coords += list(pos[i])
        return forward_kinematics(*coords)

    def get_centroid(self):
        f = self.get_current_formation()
        xk = 'x_h' if 'x_h' in f else 'x_c'
        yk = 'y_h' if 'y_h' in f else 'y_c'
        return np.array([f[xk], f[yk]])

    def sample_field_at_robots(self):
        return [robot.sample_field(self.field) for robot in self.robots]

    def move(self, control_primitive):
        current = self.get_current_formation()
        vx_c, vy_c = control_primitive(self)

        # Formation errors (proportional control)
        shape_vel = np.zeros(len(STATE_VARS))
        col = {v: i for i, v in enumerate(STATE_VARS)}
        xk = 'x_h' if 'x_h' in current else 'x_c'
        yk = 'y_h' if 'y_h' in current else 'y_c'
        shape_vel[col[xk]] = vx_c
        shape_vel[col[yk]] = vy_c
        shape_vel[col.get('theta_c', -1)] = 0.0  # no spin by default

        for i in range(1, 6):
            r_key = f'r_{i}'
            if r_key in col:
                shape_vel[col[r_key]] = self.position_gain * (
                    getattr(self, f'desired_r_{i}') - current.get(r_key, 0))
        for i in range(2, 6):
            g_key = f'gamma_{i}'
            if g_key in col:
                err = getattr(self, f'desired_gamma_{i}') - current.get(g_key, 0)
                err = (err + 3.14159) % (2*3.14159) - 3.14159
                shape_vel[col[g_key]] = self.angle_gain * err

        J_inv = inverse_jacobian(current)
        robot_vel = J_inv @ shape_vel

        for i, robot in enumerate(self.robots):
            robot.command_velocity(robot_vel[2*i], robot_vel[2*i+1])

        centroid = self.get_centroid()
        self.center_history.append(centroid.copy())
        pos = self.get_robot_positions()
        self.robot_history.append(np.array([list(pos[i+1]) for i in range(6)]))

    def reset(self, x_c=None, y_c=None):
        import math
        default = {'x_h': 0.0, 'y_h': 0.0, 'theta_c': 0.0, 'r_1': 0.3, 'r_2': 0.3, 'r_3': 0.3, 'r_4': 0.3, 'r_5': 0.3, 'gamma_2': 1.2566370614359172, 'gamma_3': 2.5132741228718345, 'gamma_4': -2.5132741228718345, 'gamma_5': -1.2566370614359172}
        default['x_c' if 'x_c' in default else 'x_h'] = x_c or 0.0
        default['y_c' if 'y_c' in default else 'y_h'] = y_c or 0.0
        positions = inverse_kinematics(default)
        for i, robot in enumerate(self.robots):
            xi, yi = positions[i+1]
            robot.set_position(xi, yi)
            robot.velocity = np.array([0.0, 0.0])
        self.center_history = []
        self.robot_history = []

    def get_center_history(self):
        return np.array(self.center_history) if self.center_history else np.array([])

    def get_robot_history(self):
        return np.array(self.robot_history) if self.robot_history else np.array([])

    def plot(self, ax):
        import matplotlib.pyplot as plt
        colors = ['blue', 'orange', 'green', 'red', 'purple', 'brown',
                  'pink', 'gray', 'olive', 'cyan']
        pos = self.get_robot_positions()
        for i in range(1, 6+1):
            xi, yi = pos[i]
            ax.scatter(xi, yi, color=colors[(i-1) % len(colors)], s=100, zorder=5)

    def plot_center(self, ax):
        c = self.get_centroid()
        ax.scatter(c[0], c[1], color='black', s=80, marker='x', zorder=5)

    def __repr__(self):
        c = self.get_centroid()
        return f"HexstarSnapCluster(centroid={c}, N=6)"
