"""
MyStarSnapCluster — generated by clusterbuilder.py
Config: cluster-of-clusters, 6 robots
State variables: ['x_c', 'y_c', 'theta_c', 'p_1', 'beta_1', 'q_1', 'L_2', 'theta_2', 'L_3', 'theta_3', 'L_4', 'theta_4']
"""
import os
import yaml
import numpy as np
from src.robot.omnibot import Omnibot
from my_star_snap_forward_kinematics import forward_kinematics
from my_star_snap_inverse_kinematics import inverse_kinematics
from my_star_snap_inverse_jacobian import inverse_jacobian, STATE_VARS


class MyStarSnapCluster:

    def __init__(self, formation_config_path, field, timestep=0.1, momentum_alpha=0.7):
        
        self.field = field
        self.timestep = timestep
        self.momentum_alpha = momentum_alpha
        self._load_formation_config(formation_config_path)
        self._initialize_robots()
        self.center_history = []
        self.robot_history = []
        self.velocity_history = []

    def _load_formation_config(self, config_path):
        if not os.path.isabs(config_path):
            script_dir = os.path.dirname(os.path.abspath(__file__))
            config_path = os.path.join(script_dir, config_path)
        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
        formation = config['formation']
        self.N = formation['num_robots']
        self.desired_p_1 = formation['p_1']
        self.desired_beta_1 = formation['beta_1']
        self.desired_q_1 = formation['q_1']
        self.desired_L_2 = formation['L_2']
        self.desired_theta_2 = formation['theta_2']
        self.desired_L_3 = formation['L_3']
        self.desired_theta_3 = formation['theta_3']
        self.desired_L_4 = formation['L_4']
        self.desired_theta_4 = formation['theta_4']
        self.position_gain = formation.get('position_gain', 1.0)
        self.angle_gain = formation.get('angle_gain', 0.1)

    def _initialize_robots(self):
        import math, random
        default = {'L_2': 0.16666666666666663, 'theta_2': 0.0, 'L_3': 0.16666666666666663, 'theta_3': 0.0, 'L_4': 0.16666666666666666, 'theta_4': 0.0, 'p_1': 0.6, 'beta_1': 0.914742952864994, 'q_1': 0.49180788932265, 'theta_c': 3.141592653589793, 'x_c': 0.0, 'y_c': 0.0}
        default['x_c' if 'x_c' in default else 'x_h'] = random.uniform(-0.5, 0.5)
        default['y_c' if 'y_c' in default else 'y_h'] = random.uniform(-0.5, 0.5)
        positions = inverse_kinematics(default)
        self.robots = [Omnibot(positions[i+1][0], positions[i+1][1],
                               self.timestep, self.momentum_alpha)
                       for i in range(6)]

    def get_robot_positions(self):
        return {i+1: tuple(self.robots[i].get_position()) for i in range(6)}

    def get_current_formation(self):
        pos = self.get_robot_positions()
        coords = []
        for i in range(1, 6+1):
            coords += list(pos[i])
        return forward_kinematics(*coords)

    def get_centroid(self):
        f = self.get_current_formation()
        xk = 'x_h' if 'x_h' in f else 'x_c'
        yk = 'y_h' if 'y_h' in f else 'y_c'
        return np.array([f[xk], f[yk]])

    def sample_field_at_robots(self):
        return [robot.sample_field(self.field) for robot in self.robots]

    def move(self, control_primitive):
        current = self.get_current_formation()
        vx_c, vy_c = control_primitive(self)

        # Formation errors (proportional control)
        shape_vel = np.zeros(len(STATE_VARS))
        col = {v: i for i, v in enumerate(STATE_VARS)}
        xk = 'x_h' if 'x_h' in current else 'x_c'
        yk = 'y_h' if 'y_h' in current else 'y_c'
        shape_vel[col[xk]] = vx_c
        shape_vel[col[yk]] = vy_c
        shape_vel[col.get('theta_c', -1)] = 0.0  # no spin by default

        desired_shape = {"p_1": self.desired_p_1, "beta_1": self.desired_beta_1, "q_1": self.desired_q_1, "L_2": self.desired_L_2, "theta_2": self.desired_theta_2, "L_3": self.desired_L_3, "theta_3": self.desired_theta_3, "L_4": self.desired_L_4, "theta_4": self.desired_theta_4}
        for v, desired in desired_shape.items():
            if v in col:
                err = desired - current.get(v, 0)
                gain = self.angle_gain if 'theta' in v or 'beta' in v else self.position_gain
                shape_vel[col[v]] = gain * err

        J_inv = inverse_jacobian(current)
        robot_vel = J_inv @ shape_vel

        for i, robot in enumerate(self.robots):
            robot.command_velocity(robot_vel[2*i], robot_vel[2*i+1])

        centroid = self.get_centroid()
        self.center_history.append(centroid.copy())
        pos = self.get_robot_positions()
        self.robot_history.append(np.array([list(pos[i+1]) for i in range(6)]))

    def reset(self, x_c=None, y_c=None):
        import math
        default = {'L_2': 0.16666666666666663, 'theta_2': 0.0, 'L_3': 0.16666666666666663, 'theta_3': 0.0, 'L_4': 0.16666666666666666, 'theta_4': 0.0, 'p_1': 0.6, 'beta_1': 0.914742952864994, 'q_1': 0.49180788932265, 'theta_c': 3.141592653589793, 'x_c': 0.0, 'y_c': 0.0}
        default['x_c' if 'x_c' in default else 'x_h'] = x_c or 0.0
        default['y_c' if 'y_c' in default else 'y_h'] = y_c or 0.0
        positions = inverse_kinematics(default)
        for i, robot in enumerate(self.robots):
            xi, yi = positions[i+1]
            robot.set_position(xi, yi)
            robot.velocity = np.array([0.0, 0.0])
        self.center_history = []
        self.robot_history = []

    def get_center_history(self):
        return np.array(self.center_history) if self.center_history else np.array([])

    def get_robot_history(self):
        return np.array(self.robot_history) if self.robot_history else np.array([])

    def plot(self, ax):
        import matplotlib.pyplot as plt
        colors = ['blue', 'orange', 'green', 'red', 'purple', 'brown',
                  'pink', 'gray', 'olive', 'cyan']
        pos = self.get_robot_positions()
        for i in range(1, 6+1):
            xi, yi = pos[i]
            ax.scatter(xi, yi, color=colors[(i-1) % len(colors)], s=100, zorder=5)

    def plot_center(self, ax):
        c = self.get_centroid()
        ax.scatter(c[0], c[1], color='black', s=80, marker='x', zorder=5)

    def __repr__(self):
        c = self.get_centroid()
        return f"MyStarSnapCluster(centroid={c}, N=6)"
